[Definition]
failregex = ^.*check_password for user \[.*\] failed: NT_STATUS_WRONG_PASSWORD.*remote_address \[IPV4\]:<HOST>.*$
            ^.*Authentication for user \[.*\] -> \[.*\] failed with NT_STATUS_NO_SUCH_USER.*remote_address \[IPV4\]:<HOST>.*$
            ^.*\[<HOST>\]\s+lib/audit\.c:.*smbd_audit_.*: (Failed|failed) login.*$

ignoreregex =

